import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface ExportButtonProps {
  propertyName?: string;
}

const ExportButton = ({ propertyName }: ExportButtonProps) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleExport = async () => {
    const resultsEl = document.getElementById("report-capture-area");
    if (!resultsEl) {
      toast("No analysis data to export. Run an analysis first.");
      return;
    }

    setIsGenerating(true);
    toast("Generating high-resolution report...");

    try {
      const canvas = await html2canvas(resultsEl, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: "#0A0F1E",
        logging: false,
      });

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - margin * 2;
      const date = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
      const name = propertyName?.trim() || "Property";
      const safeName = name.replace(/[^a-zA-Z0-9_ -]/g, "_");

      // Header
      pdf.setFillColor(10, 15, 30);
      pdf.rect(0, 0, pageWidth, pageHeight, "F");

      // Logo text
      pdf.setTextColor(0, 212, 255);
      pdf.setFontSize(20);
      pdf.setFont("helvetica", "bold");
      pdf.text("C", margin, 14);
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(16);
      pdf.text("ClimateVault", margin + 8, 14);

      // Date
      pdf.setFontSize(9);
      pdf.setTextColor(160, 170, 190);
      pdf.text(date, pageWidth - margin, 14, { align: "right" });

      // Divider
      pdf.setDrawColor(0, 212, 255);
      pdf.setLineWidth(0.5);
      pdf.line(margin, 19, pageWidth - margin, 19);

      // Title
      pdf.setFontSize(14);
      pdf.setTextColor(255, 255, 255);
      pdf.setFont("helvetica", "bold");
      pdf.text(`Climate Risk & TCFD Disclosure Report`, margin, 28);
      pdf.setFontSize(11);
      pdf.setTextColor(0, 212, 255);
      pdf.text(name, margin, 35);

      // Content image
      const headerHeight = 40;
      const footerHeight = 12;
      const availableHeight = pageHeight - headerHeight - footerHeight;
      const imgAspect = canvas.height / canvas.width;
      let imgW = contentWidth;
      let imgH = imgW * imgAspect;

      if (imgH > availableHeight) {
        imgH = availableHeight;
        imgW = imgH / imgAspect;
      }

      const xOffset = margin + (contentWidth - imgW) / 2;
      pdf.addImage(imgData, "PNG", xOffset, headerHeight, imgW, imgH);

      // Footer
      pdf.setFontSize(8);
      pdf.setTextColor(120, 130, 150);
      pdf.text(
        "Page 1 of 1 | Generated by ClimateVault Intelligence",
        pageWidth / 2,
        pageHeight - 6,
        { align: "center" }
      );

      pdf.save(`ClimateVault_Report_${safeName}.pdf`);
      toast.success("Report downloaded successfully.");
    } catch (err) {
      console.error("PDF generation failed:", err);
      toast.warning("PDF generation failed. Please try again or print the page.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="mt-12 flex justify-center">
      <Button
        onClick={handleExport}
        disabled={isGenerating}
        className="w-full max-w-md bg-primary hover:bg-primary/85 text-primary-foreground font-bold py-4 h-14 rounded-xl text-base glow-primary-intense transition-all"
      >
        {isGenerating ? (
          <Loader2 className="h-5 w-5 mr-2 animate-spin" />
        ) : (
          <Download className="h-5 w-5 mr-2" />
        )}
        {isGenerating ? "Generating Report..." : "Download TCFD/CSRD Climate Risk Report (PDF)"}
      </Button>
    </div>
  );
};

export default ExportButton;
